package demo.model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 20 09:47:49 MST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpByEmailImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmpByEmailImpl() {
    }
}

